// lib/elliott.mjs — Elliott Wave counting. ANALYSIS ONLY, zero dependencies.
//
// SCOPE (v1, deliberate): impulse (5 waves) and SIMPLE corrections — zigzag, flat and
// contracting triangle. Diagonals, truncations and complex combinations (WXY, double and
// triple threes) are NOT counted; where the structure looks like one, this reports low
// confidence rather than forcing a label it cannot justify.
//
// HONESTY, because Elliott Wave invites the opposite:
//   - An algorithm produces ONE rule-valid count out of several. It is an interpretation,
//     not a measurement. So this module always returns ALTERNATES alongside the primary
//     count, and every count carries the exact price that INVALIDATES it.
//   - Counts re-label as new bars print, and right-hand-edge ambiguity is worst exactly
//     where you would want to trade. Confidence is capped at 75% for that reason — a
//     wave count should never present itself as being as certain as a moving average.
//   - Alternate counts are generated by re-running the swing detection at several
//     significance thresholds: different thresholds legitimately see different degrees,
//     which is precisely where real disagreement between analysts comes from.
//
// The three HARD rules are absolute — a count violating any one is discarded outright,
// never shown with a lower score:
//   R1  Wave 2 never retraces more than 100% of wave 1
//   R2  Wave 3 is never the shortest of waves 1, 3 and 5
//   R3  Wave 4 never enters wave 1's price territory
// Everything else (Fibonacci proportion, alternation, channelling, volume and momentum
// personality) is a GUIDELINE and only contributes to the score.

import { r2, clamp, atr, lineFit, evidence, zigzag, rsi, sma } from './indicators.mjs';

const TF_LABEL = { '1M': 'Monthly', '1W': 'Weekly', '1D': 'Daily', '4H': '4-Hour' };
// Wave degree by timeframe, with Elliott's conventional notation per degree.
const DEGREE = {
  '1M': { name: 'Primary', mark: ['①', '②', '③', '④', '⑤'], corr: ['Ⓐ', 'Ⓑ', 'Ⓒ'] },
  '1W': { name: 'Intermediate', mark: ['(1)', '(2)', '(3)', '(4)', '(5)'], corr: ['(A)', '(B)', '(C)'] },
  '1D': { name: 'Minor', mark: ['1', '2', '3', '4', '5'], corr: ['A', 'B', 'C'] },
  '4H': { name: 'Minute', mark: ['(i)', '(ii)', '(iii)', '(iv)', '(v)'], corr: ['(a)', '(b)', '(c)'] },
};
const MAX_CONFIDENCE = 75;      // see header — never present a count as near-certain
const RETR = [0.382, 0.5, 0.618, 0.786];
const EXT = [1.0, 1.618, 2.618];

// Proximity of an actual ratio to the nearest ideal Fibonacci value, 0..1.
const fibProx = (actual, ideals) =>
  clamp(1 - Math.min(...ideals.map(i => Math.abs(actual - i) / i)) / 0.2);
const nearestFib = (actual, ideals) =>
  ideals.reduce((b, i) => Math.abs(actual - i) < Math.abs(actual - b) ? i : b, ideals[0]);

const len = (a, b) => Math.abs(b - a);

// ---- impulse ---------------------------------------------------------------
// `k` pivots are taken from the right edge: k=6 means waves 1-5 are all in place, k=5
// means 1-4 with 5 forming, and so on. Trying several k is what lets the module say
// "wave 3 of 5, in progress" instead of only ever labelling completed structures.
function tryImpulse(zz, bars, A, k) {
  if (zz.length < k) return null;
  const p = zz.slice(-k);
  const up = p[0].kind === 'L';
  // Pivots must strictly alternate for a valid wave sequence.
  for (let i = 1; i < p.length; i++) if (p[i].kind === p[i - 1].kind) return null;
  if (up !== (p[0].kind === 'L')) return null;
  const v = p.map(x => x.p);
  const dir = up ? 1 : -1;
  const nWaves = k - 1;                       // waves identified so far (1..5)
  if (nWaves < 3 || nWaves > 5) return null;

  // Directional sanity: each odd wave must advance, each even wave must retrace.
  for (let i = 1; i <= nWaves; i++) {
    const adv = (v[i] - v[i - 1]) * dir;
    if (i % 2 === 1 && adv <= 0) return null;
    if (i % 2 === 0 && adv >= 0) return null;
  }

  const L = [];                               // wave lengths, 1-indexed
  for (let i = 1; i <= nWaves; i++) L[i] = len(v[i - 1], v[i]);

  // ---- HARD RULES ----
  const rules = [];
  // R1: wave 2 never retraces more than 100% of wave 1.
  const r1 = nWaves < 2 ? null : (up ? v[2] > v[0] : v[2] < v[0]);
  rules.push({ id: 'R1', label: 'Wave 2 does not retrace more than 100% of wave 1', pass: r1 !== false,
    detail: nWaves < 2 ? 'not yet applicable' : `wave 2 retraced ${r2(L[2] / L[1] * 100)}% of wave 1` });
  // R2: wave 3 is never the shortest of 1, 3, 5.
  const r2rule = nWaves < 5 ? null : !(L[3] < L[1] && L[3] < L[5]);
  rules.push({ id: 'R2', label: 'Wave 3 is not the shortest of waves 1, 3 and 5', pass: r2rule !== false,
    detail: nWaves < 5 ? 'wave 5 not complete — not yet testable' : `lengths ${r2(L[1])} / ${r2(L[3])} / ${r2(L[5])}` });
  // R3: wave 4 never enters wave 1's territory.
  const r3 = nWaves < 4 ? null : (up ? v[4] > v[1] : v[4] < v[1]);
  rules.push({ id: 'R3', label: "Wave 4 does not enter wave 1's price territory", pass: r3 !== false,
    detail: nWaves < 4 ? 'wave 4 not complete — not yet testable' : `wave 4 ${r2(v[4])} vs wave 1 ${r2(v[1])}` });
  if (rules.some(x => x.pass === false)) return null;      // discarded, never downgraded

  // ---- GUIDELINES ----
  const ratios = [];
  if (nWaves >= 2) ratios.push({ w: 2, of: 'Wave 2 : Wave 1', kind: 'retracement', actual: L[2] / L[1], ideals: RETR });
  if (nWaves >= 3) ratios.push({ w: 3, of: 'Wave 3 : Wave 1', kind: 'extension', actual: L[3] / L[1], ideals: EXT });
  if (nWaves >= 4) ratios.push({ w: 4, of: 'Wave 4 : Wave 3', kind: 'retracement', actual: L[4] / L[3], ideals: RETR });
  if (nWaves >= 5) ratios.push({ w: 5, of: 'Wave 5 : Wave 1', kind: 'extension', actual: L[5] / L[1], ideals: EXT });
  const fibScore = ratios.length ? ratios.reduce((s, x) => s + fibProx(x.actual, x.ideals), 0) / ratios.length : 0.5;

  // Alternation: wave 2 and wave 4 should differ in character — one sharp, one sideways.
  let alternation = 0.5, altNote = 'not yet testable';
  if (nWaves >= 4) {
    const d2 = L[2] / L[1], d4 = L[4] / L[3];
    const t2 = p[2].i - p[1].i, t4 = p[4].i - p[3].i;
    const differs = (d2 > 0.55 && d4 < 0.45) || (d2 < 0.45 && d4 > 0.55) || (t4 > 1.6 * t2) || (t2 > 1.6 * t4);
    alternation = differs ? 1 : 0.25;
    altNote = differs
      ? `wave 2 ${d2 > d4 ? 'sharp' : 'shallow'} (${r2(d2 * 100)}%, ${t2} bars) vs wave 4 ${d4 > d2 ? 'sharp' : 'shallow'} (${r2(d4 * 100)}%, ${t4} bars)`
      : `wave 2 and wave 4 are similar in depth and duration (${r2(d2 * 100)}% / ${r2(d4 * 100)}%) — alternation absent`;
  }

  // Wave 3 extended: the commonest and most reliable impulse signature.
  const w3ext = nWaves >= 3 ? L[3] / L[1] : null;
  const w3Extended = w3ext != null && w3ext >= 1.5;

  // Channelling: 0-2-4 and 1-3 should be roughly parallel.
  let channel = 0.5;
  if (nWaves >= 4) {
    const base = lineFit([{ i: p[0].i, p: v[0] }, { i: p[2].i, p: v[2] }, { i: p[4].i, p: v[4] }]);
    const top = lineFit([{ i: p[1].i, p: v[1] }, { i: p[3].i, p: v[3] }]);
    if (base && top && base.slope && top.slope) {
      const ratio = top.slope / base.slope;
      channel = ratio > 0 ? clamp(1 - Math.abs(1 - ratio) / 1.2) : 0.1;
    }
  }

  // Volume personality: wave 3 should carry more volume than wave 1.
  const volOf = (a, b) => sma(bars.slice(a, b + 1).map(x => x.v || 0), Math.max(1, b - a + 1));
  let volOK = null;
  if (nWaves >= 3) {
    const v1 = volOf(p[0].i, p[1].i), v3 = volOf(p[2].i, p[3].i);
    if (v1 && v3) volOK = v3 > v1;
  }
  // Momentum: wave 5 should diverge against wave 3 (lower RSI on a higher high).
  let divergence = null;
  if (nWaves >= 5) {
    const r3i = rsi(bars.slice(0, p[3].i + 1)), r5i = rsi(bars.slice(0, p[5].i + 1));
    if (r3i != null && r5i != null) divergence = up ? r5i < r3i : r5i > r3i;
  }

  const guideline = evidence([
    [4, fibScore], [3, alternation], [2, channel],
    [2, w3Extended ? 1 : 0.4],
    [2, volOK == null ? 0.5 : volOK ? 1 : 0.2],
    [1, divergence == null ? 0.5 : divergence ? 1 : 0.3],
  ]);

  return {
    structure: 'Impulse', direction: up ? 'up' : 'down', up, dir,
    waves: nWaves, pivots: p, values: v, lengths: L,
    rules, ratios, guideline, fibScore, alternation, altNote, channel,
    w3Extended, w3ext, volOK, divergence,
    inProgress: !!p[p.length - 1].provisional,
  };
}

// ---- simple corrections ----------------------------------------------------
// Zigzag (5-3-5, sharp), flat (3-3-5, shallow B) and contracting triangle.
function tryCorrection(zz, bars, A, k) {
  if (zz.length < k) return null;
  const p = zz.slice(-k);
  for (let i = 1; i < p.length; i++) if (p[i].kind === p[i - 1].kind) return null;
  const v = p.map(x => x.p);
  const down = p[0].kind === 'H';            // a correction of a prior advance
  const nLegs = k - 1;

  // ---- contracting triangle: five legs, each smaller than the one two before it ----
  if (nLegs === 5) {
    const L = [];
    for (let i = 1; i <= 5; i++) L[i] = len(v[i - 1], v[i]);
    const contracting = L[3] < L[1] && L[4] < L[2] && L[5] < L[3];
    if (!contracting) return null;
    const guideline = evidence([
      [3, clamp(1 - L[5] / L[1])], [3, clamp(1 - L[3] / L[1])],
      [2, clamp(1 - L[4] / L[2])], [2, 0.7],
    ]);
    return {
      structure: 'Contracting Triangle', direction: down ? 'down' : 'up', up: !down, dir: down ? -1 : 1,
      waves: 5, labels: ['A', 'B', 'C', 'D', 'E'], pivots: p, values: v, lengths: L,
      rules: [{ id: 'T1', label: 'Each leg contracts against the leg two before it', pass: true,
        detail: `legs ${L.slice(1).map(x => r2(x)).join(' / ')}` }],
      ratios: [{ w: 5, of: 'Leg E : Leg A', kind: 'contraction', actual: L[5] / L[1], ideals: RETR }],
      guideline, inProgress: !!p[p.length - 1].provisional,
      note: 'Triangles form in wave 4 or wave B and precede a final thrust in the direction of the prior trend.',
    };
  }

  // ---- zigzag / flat: three legs A-B-C ----
  if (nLegs !== 3) return null;
  const A_ = len(v[0], v[1]), B_ = len(v[1], v[2]), C_ = len(v[2], v[3]);
  const bRetr = B_ / A_;
  if (bRetr > 1.4) return null;                        // B beyond this is not a simple correction
  const isFlat = bRetr >= 0.9;
  const structure = isFlat ? 'Flat' : 'Zigzag';
  // A zigzag's C should carry beyond A's extreme; a flat's C roughly equals A.
  const cBeyond = down ? v[3] < v[1] : v[3] > v[1];
  const guideline = evidence([
    [3, fibProx(bRetr, isFlat ? [0.9, 1.0] : RETR)],
    [3, fibProx(C_ / A_, isFlat ? [1.0, 1.272] : [0.618, 1.0, 1.618])],
    [2, cBeyond ? 1 : 0.35],
    [2, isFlat ? 0.7 : 0.85],
  ]);
  return {
    structure, direction: down ? 'down' : 'up', up: !down, dir: down ? -1 : 1,
    waves: 3, labels: ['A', 'B', 'C'], pivots: p, values: v, lengths: [null, A_, B_, C_],
    rules: [{ id: 'C1', label: 'Wave B does not exceed the start of wave A by more than 40%', pass: true,
      detail: `wave B retraced ${r2(bRetr * 100)}% of wave A` }],
    ratios: [
      { w: 2, of: 'Wave B : Wave A', kind: 'retracement', actual: bRetr, ideals: isFlat ? [0.9, 1.0] : RETR },
      { w: 3, of: 'Wave C : Wave A', kind: 'extension', actual: C_ / A_, ideals: isFlat ? [1.0, 1.272] : [0.618, 1.0, 1.618] },
    ],
    guideline, cBeyond, inProgress: !!p[p.length - 1].provisional,
    note: isFlat ? 'Flats are continuation patterns — they signal an underlying trend still in force.'
      : 'Zigzags are sharp counter-trend corrections, typical of wave 2 and wave A.',
  };
}

// ---- position, invalidation, projections -----------------------------------
// The invalidation level is the single most useful number a wave count produces: the
// price at which this interpretation is objectively dead and must be re-labelled.
function positionOf(c, px) {
  const v = c.values, p = c.pivots, up = c.up;
  if (c.structure === 'Impulse') {
    const n = c.waves;
    const inProg = c.inProgress;
    const label = inProg ? n : n;                       // the newest wave is the live one
    const current = inProg ? label : label + 1;         // if complete, the next wave is forming
    const complete = !inProg && n >= 5;
    const invalidation = {
      2: v[0],                                          // wave 2 cannot pass wave 1's origin
      3: v[2],                                          // wave 3 must exceed wave 1's high
      4: v[1],                                          // wave 4 cannot enter wave 1
      5: v[4],                                          // wave 5 must hold wave 4's extreme
    }[Math.min(current, 5)] ?? v[0];
    return { waveNumber: Math.min(current, 5), inProgress: inProg, complete, invalidation,
      invalidationRule: complete
        ? 'the completed impulse is negated if price retraces beyond its own origin'
        : { 2: 'wave 2 may not retrace 100% of wave 1', 3: 'wave 3 must exceed the wave 1 extreme',
            4: "wave 4 may not enter wave 1's territory", 5: 'wave 5 must hold beyond the wave 4 extreme' }[Math.min(current, 5)] };
  }
  const idx = Math.min(c.waves, c.labels.length);
  return { waveNumber: idx, waveLabel: c.labels[idx - 1], inProgress: c.inProgress,
    invalidation: v[0], invalidationRule: 'the correction may not exceed its own origin' };
}

function projectionsFor(c, pos, px) {
  const out = [], v = c.values, L = c.lengths, up = c.up, sgn = up ? 1 : -1;
  const add = (label, basis, price) => {
    if (price == null || !isFinite(price)) return;
    out.push({ label, basis, price: r2(price), distPct: r2((price - px) / px * 100) });
  };
  if (c.structure === 'Impulse') {
    const w = pos.waveNumber;
    if (w === 3 && L[1]) {
      add('Wave 3 target', '1.618 × wave 1 from the wave 2 low', v[2] + sgn * 1.618 * L[1]);
      add('Wave 3 extended', '2.618 × wave 1 from the wave 2 low', v[2] + sgn * 2.618 * L[1]);
    } else if (w === 4 && L[3]) {
      add('Wave 4 shallow', '0.382 retracement of wave 3', v[3] - sgn * 0.382 * L[3]);
      add('Wave 4 typical', '0.5 retracement of wave 3', v[3] - sgn * 0.5 * L[3]);
    } else if (w === 5 && L[1]) {
      add('Wave 5 equality', 'wave 5 = wave 1, from the wave 4 extreme', v[4] + sgn * L[1]);
      if (L[3]) add('Wave 5 extended', '0.618 × (wave 1 + wave 3) from the wave 4 extreme', v[4] + sgn * 0.618 * (L[1] + L[3]));
    } else if (w === 2 && L[1]) {
      add('Wave 2 typical', '0.618 retracement of wave 1', v[1] - sgn * 0.618 * L[1]);
    }
  } else if (c.structure !== 'Contracting Triangle' && L[1]) {
    add('Wave C equality', 'wave C = wave A, from the wave B extreme', v[2] + (c.up ? 1 : -1) * L[1]);
    add('Wave C 1.618×A', '1.618 × wave A from the wave B extreme', v[2] + (c.up ? 1 : -1) * 1.618 * L[1]);
  }
  return out;
}

// ---- per-timeframe: generate, validate and rank candidate counts ------------
export function countTF(bars, tf) {
  const label = TF_LABEL[tf] || tf;
  const deg = DEGREE[tf] || DEGREE['1D'];
  if (!bars || bars.length < 40) {
    return { tf, label, degree: deg.name, ok: false, error: `Only ${bars?.length || 0} bars — a wave count needs ≥40.`, counts: [] };
  }
  const win = Math.min(bars.length, tf === '1M' ? 60 : tf === '1W' ? 120 : 180);
  const w = bars.slice(-win);
  const A = atr(w, 14);
  const px = w[w.length - 1].c;
  if (!A) return { tf, label, degree: deg.name, ok: false, error: 'Cannot measure volatility.', counts: [] };

  const seen = new Set(), counts = [];
  // Several significance thresholds: different thresholds legitimately resolve different
  // degrees, and that is exactly where genuine alternate counts come from.
  for (const mult of [1.0, 1.7, 2.6, 3.8]) {
    const zz = zigzag(w, Math.max(mult * A, mult * 0.01 * px), 3);
    if (zz.length < 4) continue;
    for (const k of [6, 5, 4]) {
      for (const c of [tryImpulse(zz, w, A, k), tryCorrection(zz, w, A, k)]) {
        if (!c) continue;
        const pos = positionOf(c, px);
        // Coverage: the share of the analysed window this count spans. A count that
        // explains three months of price action is a better reading than one that labels
        // the last two weeks, and without this the short 3-leg corrections — which are
        // far easier to satisfy than a 5-leg impulse — crowd out every impulse count.
        const span = c.pivots[c.pivots.length - 1].i - c.pivots[0].i;
        const coverage = clamp(span / win);
        if (coverage < 0.25) continue;                 // a right-edge micro-count explains nothing
        const key = `${c.structure}|${c.direction}|${pos.waveNumber}|${pos.inProgress}|${!!pos.complete}`;
        if (seen.has(key)) continue;
        seen.add(key);
        // Confidence: guideline conformance, how much of the chart the count explains, and
        // a structural preference for the impulse (a 5-wave reading accounts for more than
        // a 3-wave one). Capped — see the header.
        const structural = c.structure === 'Impulse' ? 100 : 62;
        const conf = Math.min(MAX_CONFIDENCE, Math.round(
          0.55 * c.guideline + 0.25 * coverage * 100 + 0.20 * structural));
        counts.push({
          structure: c.structure, direction: c.direction, degree: deg.name, tf, tfLabel: label,
          waveNumber: pos.waveNumber, waveLabel: c.labels ? pos.waveLabel : deg.mark[Math.min(pos.waveNumber, 5) - 1],
          position: c.labels
            ? `Wave ${pos.waveLabel} of a ${c.structure.toLowerCase()}`
            : pos.complete
              ? `Five-wave ${c.direction} impulse complete — a correction of it is the expected next move`
              : `Wave ${deg.mark[Math.min(pos.waveNumber, 5) - 1]} of ${c.direction === 'up' ? 'an up' : 'a down'} impulse`,
          inProgress: pos.inProgress, complete: !!pos.complete,
          invalidation: r2(pos.invalidation), invalidationRule: pos.invalidationRule,
          ruleCompliance: `${c.rules.filter(x => x.pass).length}/${c.rules.length}`,
          rules: c.rules, guidelineScore: r2(c.guideline / 10), confidence: conf,
          swingThreshold: `${mult}× ATR`, coverage: r2(coverage * 100),
          waves: c.pivots.slice(1).map((pv, i) => {
            const from = c.values[i], to = c.values[i + 1];
            const ratio = c.ratios.find(r => r.w === i + 1);
            return {
              label: c.labels ? c.labels[i] : deg.mark[Math.min(i, 4)],
              from: r2(from), to: r2(to), movePct: r2((to - from) / from * 100),
              atr: r2(Math.abs(to - from) / A), bars: pv.i - c.pivots[i].i,
              fib: ratio ? `${r2(ratio.actual)} (${ratio.kind}, nearest ${nearestFib(ratio.actual, ratio.ideals)})` : null,
              provisional: !!pv.provisional,
            };
          }),
          ratios: c.ratios.map(r => ({ of: r.of, kind: r.kind, actual: r2(r.actual),
            nearestIdeal: nearestFib(r.actual, r.ideals), proximity: r2(fibProx(r.actual, r.ideals) * 100) })),
          projections: projectionsFor(c, pos, px),
          personality: [
            { check: 'Wave 2 / wave 4 alternation', pass: c.alternation == null ? null : c.alternation > 0.5, detail: c.altNote || 'n/a' },
            { check: 'Wave 3 extended (≥1.5 × wave 1)', pass: c.w3Extended ?? null, detail: c.w3ext ? `wave 3 is ${r2(c.w3ext)}× wave 1` : 'not applicable' },
            { check: 'Wave 3 volume exceeds wave 1', pass: c.volOK ?? null, detail: c.volOK == null ? 'volume not comparable' : c.volOK ? 'confirmed' : 'wave 3 traded on lighter volume — atypical' },
            { check: 'Wave 5 momentum divergence', pass: c.divergence ?? null, detail: c.divergence == null ? 'wave 5 not complete' : c.divergence ? 'RSI diverged against price' : 'no divergence — wave 5 may extend' },
            { check: 'Channel containment (0-2-4 vs 1-3)', pass: c.channel == null ? null : c.channel > 0.5, detail: c.channel == null ? 'n/a' : `parallelism ${r2(c.channel * 100)}%` },
          ].filter(x => x.detail !== 'not applicable'),
          note: c.note || null,
        });
      }
    }
  }
  counts.sort((a, b) => b.confidence - a.confidence || b.guidelineScore - a.guidelineScore);
  return { tf, label, degree: deg.name, ok: counts.length > 0, counts: counts.slice(0, 4),
    error: counts.length ? null : 'No rule-valid impulse or simple correction found at any swing threshold.',
    close: r2(px), atr: r2(A), bars: bars.length };
}

// ---- report ----------------------------------------------------------------
export function buildElliott(series) {
  const order = ['1M', '1W', '1D', '4H'];
  const tfs = {};
  for (const tf of order) {
    const s = series.tfs?.[tf];
    tfs[tf] = s?.ok ? countTF(s.bars, tf)
      : { tf, label: TF_LABEL[tf], degree: DEGREE[tf].name, ok: false, error: s?.error || 'No data.', counts: [] };
  }

  // The Daily (Minor degree) is the actionable count; fall back through the others.
  const primaryTF = ['1D', '1W', '4H', '1M'].find(tf => tfs[tf].ok) || null;
  const primary = primaryTF ? tfs[primaryTF].counts[0] : null;
  const price = tfs['1D']?.close ?? tfs['4H']?.close ?? tfs['1W']?.close ?? null;

  // Alternates: the rest of the primary timeframe's valid counts, plus the best count
  // from each other timeframe when it implies a different direction.
  const alternates = [];
  if (primaryTF) tfs[primaryTF].counts.slice(1).forEach(c => alternates.push({ ...c, from: 'same timeframe, different swing threshold' }));
  for (const tf of order) {
    if (tf === primaryTF || !tfs[tf].ok) continue;
    const c = tfs[tf].counts[0];
    if (c && primary && c.direction !== primary.direction) alternates.push({ ...c, from: `${tfs[tf].label} degree — conflicts with the primary count` });
  }
  alternates.sort((a, b) => b.confidence - a.confidence);

  const nesting = order.filter(tf => tfs[tf].ok).map(tf => {
    const c = tfs[tf].counts[0];
    return { tf: tfs[tf].label, degree: tfs[tf].degree, position: c.position, structure: c.structure,
      direction: c.direction, confidence: c.confidence, invalidation: c.invalidation };
  });
  const dirs = nesting.map(n => n.direction);
  const aligned = dirs.length >= 2 && dirs.every(d => d === dirs[0]);

  const conclusion = [];
  if (!primary) {
    conclusion.push('No rule-valid Elliott count on any timeframe — the structure is currently unlabelable within this scope (impulse, zigzag, flat, contracting triangle).');
    conclusion.push('This is an honest "no count", not a failure: diagonals, truncations and complex corrections are deliberately not counted.');
  } else {
    conclusion.push(`Primary count: ${tfs[primaryTF].label} (${tfs[primaryTF].degree} degree) — ${primary.position}`
      + `${primary.inProgress ? ', in progress' : ', complete'} at ${primary.confidence}% confidence, rules ${primary.ruleCompliance}.`);
    conclusion.push(`INVALIDATION ${primary.invalidation} — ${primary.invalidationRule}. Beyond that price this count is dead and must be re-labelled.`);
    if (primary.projections.length) {
      conclusion.push('Projections: ' + primary.projections.map(p => `${p.label} ${p.price} (${p.distPct > 0 ? '+' : ''}${p.distPct}%)`).join(' · ') + '.');
    }
    conclusion.push(aligned
      ? `All ${nesting.length} timeframes count in the same direction (${dirs[0]}) — degrees are nested consistently.`
      : 'Timeframe degrees disagree on direction — treat the count as low-conviction and defer to the higher degree.');
    conclusion.push(`${alternates.length} alternate count${alternates.length === 1 ? '' : 's'} remain rule-valid. A wave count is one interpretation among several, not a measurement — trade the invalidation level, not the label.`);
  }

  return {
    ok: true, ts: Date.now(), symbol: series.symbol, market: series.market, source: series.source,
    price, scope: 'Impulse and simple corrections (zigzag, flat, contracting triangle). Diagonals, truncations and complex combinations are not counted.',
    primary: primary ? { ...primary, timeframe: tfs[primaryTF].label } : null,
    alternates: alternates.slice(0, 5),
    nesting, aligned,
    timeframes: order.map(tf => ({ tf, label: tfs[tf].label, degree: tfs[tf].degree, ok: tfs[tf].ok,
      error: tfs[tf].error, close: tfs[tf].close, counts: tfs[tf].counts.length })),
    conclusion,
  };
}
